@startuml
'https://plantuml.com/class-diagram

class Solution41 {
    call : ProcessFile
    -name : String
    input : Scanner
    names : List<String>
    +main(args : String[])
    }

class ProcessFile {
    +toStringList(original : List<String>)
    -names : String[]
    -callFile : PrintWriter
    +printOutputFile (names : String[])
}

Solution41 o--> ProcessFile
@enduml