@startuml
'https://plantuml.com/class-diagram


class WordFrequencyFinder {

    +main(args : String[])

    }

WordFrequencyFinder o--> SortData
class SortData {

    +sortList(data : List<String>) : String[]
    +differentWords(allWords : String[]) : String
    +stars(words : String[], counter : int[]) : String

    }

@enduml